name: Deploy PPDB to Cloud run

on:
  push:
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      
      - name: Set Up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with: 
            project_id: deploy-api-phyton
            service_account_key: ${{secrets.GCLOUD_AUTH}}

      - name: Configure Docker to use gcloud 
        run: |
            gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet
      # - name: Set Environment Variables
      #   run: |
      #       echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> $GITHUB_ENV
      #       echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
      #       echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
      #       echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> $GITHUB_ENV
      #       echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
      #       echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> $GITHUB_ENV
      #       echo "DB_USERNAME_PROD=${{ secrets.DB_USERNAME_PROD }}" >> $GITHUB_ENV
      #       echo "DB_PASSWORD_PROD=${{ secrets.DB_PASSWORD_PROD }}" >> $GITHUB_ENV
      #       echo "DB_DATABASE_PROD=${{ secrets.DB_DATABASE_PROD }}" >> $GITHUB_ENV
      #       echo "DB_HOST_PROD=${{ secrets.DB_HOST_PROD }}" >> $GITHUB_ENV
      #       echo "DB_DIALECT_PROD=${{ secrets.DB_DIALECT_PROD }}" >> $GITHUB_ENV
        
      - name: Build and Push Docker Image 
        run: |
            export IMAGE_TAG=$(git rev-parse --short ${{github.sha}})
            export IMAGE_NAME=asia-southeast1-docker.pkg.dev/deploy-api-phyton/ppdb/ppdb_sekolah:${IMAGE_TAG}
            docker build -t ${IMAGE_NAME} .
            docker push ${IMAGE_NAME}
      - name: Deploy to Cloud Run
        run: |
            export IMAGE_TAG=$(git rev-parse --short ${{github.sha}})
            export IMAGE_NAME=asia-southeast1-docker.pkg.dev/deploy-api-phyton/ppdb/ppdb_sekolah:${IMAGE_TAG}
            gcloud run deploy ppdb-sekolah --image ${IMAGE_NAME} --region asia-southeast2 --allow-unauthenticated
        # env:
        #     CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
